// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PomodoroWebApp.Infrastructure.Data;

#nullable disable

namespace PomodoroWebApp.Infrastructure.Migrations
{
    [DbContext(typeof(PomodoroDbContext))]
    partial class PomodoroDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PomodoroWebApp.Domain.Entities.EstadisticasUsuario", b =>
                {
                    b.Property<int>("EstadisticasUsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EstadisticasUsuarioId"));

                    b.Property<int>("CiclosCompletados")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int>("MaximoTrabajoSinDescanso")
                        .HasColumnType("int");

                    b.Property<int>("MinutosDescanso")
                        .HasColumnType("int");

                    b.Property<int>("MinutosTrabajo")
                        .HasColumnType("int");

                    b.Property<int>("MinutosTrabajoPorProyecto")
                        .HasColumnType("int");

                    b.Property<int>("MinutosTrabajoPorTarea")
                        .HasColumnType("int");

                    b.Property<int>("PromedioDescanso")
                        .HasColumnType("int");

                    b.Property<int>("ProyectosCompletados")
                        .HasColumnType("int");

                    b.Property<int>("TareasCompletadas")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("EstadisticasUsuarioId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("EstadisticasUsuario");
                });

            modelBuilder.Entity("PomodoroWebApp.Domain.Entities.PomodoroSesion", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<DateTime>("HoraFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("HoraInicio")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable((string)null);

                    b.UseTpcMappingStrategy();
                });

            modelBuilder.Entity("PomodoroWebApp.Domain.Entities.Proyecto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Proyectos");
                });

            modelBuilder.Entity("PomodoroWebApp.Domain.Entities.Sesion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Ciclos")
                        .HasColumnType("int");

                    b.Property<int>("DescansoCortoId")
                        .HasColumnType("int");

                    b.Property<int?>("TareaId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DescansoCortoId");

                    b.HasIndex("TareaId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Sesiones");
                });

            modelBuilder.Entity("PomodoroWebApp.Domain.Entities.Tarea", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Prioridad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProyectoId")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("Id");

                    b.HasIndex("ProyectoId");

                    b.ToTable("Tareas");
                });

            modelBuilder.Entity("PomodoroWebApp.Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Baja")
                        .HasColumnType("bit");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("PomodoroWebApp.Domain.Entities.SesionDescanso", b =>
                {
                    b.HasBaseType("PomodoroWebApp.Domain.Entities.PomodoroSesion");

                    b.Property<bool>("EsDescansoLargo")
                        .HasColumnType("bit");

                    b.ToTable("SesionesDescanso", (string)null);
                });

            modelBuilder.Entity("PomodoroWebApp.Domain.Entities.SesionTrabajo", b =>
                {
                    b.HasBaseType("PomodoroWebApp.Domain.Entities.PomodoroSesion");

                    b.ToTable("SesionesTrabajo", (string)null);
                });

            modelBuilder.Entity("PomodoroWebApp.Domain.Entities.EstadisticasUsuario", b =>
                {
                    b.HasOne("PomodoroWebApp.Domain.Entities.Usuario", "Usuario")
                        .WithMany("EstadisticasUsuario")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("PomodoroWebApp.Domain.Entities.Proyecto", b =>
                {
                    b.HasOne("PomodoroWebApp.Domain.Entities.Usuario", "Usuario")
                        .WithMany("Proyectos")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("PomodoroWebApp.Domain.Entities.Sesion", b =>
                {
                    b.HasOne("PomodoroWebApp.Domain.Entities.SesionDescanso", "DescansoCorto")
                        .WithMany()
                        .HasForeignKey("DescansoCortoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PomodoroWebApp.Domain.Entities.Tarea", "Tarea")
                        .WithMany("Sesiones")
                        .HasForeignKey("TareaId");

                    b.HasOne("PomodoroWebApp.Domain.Entities.Usuario", "Usuario")
                        .WithMany("Sesiones")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DescansoCorto");

                    b.Navigation("Tarea");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("PomodoroWebApp.Domain.Entities.Tarea", b =>
                {
                    b.HasOne("PomodoroWebApp.Domain.Entities.Proyecto", "Proyecto")
                        .WithMany("Tareas")
                        .HasForeignKey("ProyectoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Proyecto");
                });

            modelBuilder.Entity("PomodoroWebApp.Domain.Entities.SesionDescanso", b =>
                {
                    b.HasOne("PomodoroWebApp.Domain.Entities.Sesion", null)
                        .WithOne("DescansoLargo")
                        .HasForeignKey("PomodoroWebApp.Domain.Entities.SesionDescanso", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PomodoroWebApp.Domain.Entities.SesionTrabajo", b =>
                {
                    b.HasOne("PomodoroWebApp.Domain.Entities.Sesion", null)
                        .WithOne("SesionTrabajo")
                        .HasForeignKey("PomodoroWebApp.Domain.Entities.SesionTrabajo", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PomodoroWebApp.Domain.Entities.Proyecto", b =>
                {
                    b.Navigation("Tareas");
                });

            modelBuilder.Entity("PomodoroWebApp.Domain.Entities.Sesion", b =>
                {
                    b.Navigation("DescansoLargo")
                        .IsRequired();

                    b.Navigation("SesionTrabajo")
                        .IsRequired();
                });

            modelBuilder.Entity("PomodoroWebApp.Domain.Entities.Tarea", b =>
                {
                    b.Navigation("Sesiones");
                });

            modelBuilder.Entity("PomodoroWebApp.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("EstadisticasUsuario");

                    b.Navigation("Proyectos");

                    b.Navigation("Sesiones");
                });
#pragma warning restore 612, 618
        }
    }
}
